#!/usr/bin/env bash
# GENERATED by agent-standards `install-project.sh` — edit the source in ~/.agents/hooks/cloud/.
#
# Cloud-session bridge to the central standards. Claude Code on the web starts from a
# fresh VM with only the repository's own `.claude/` on disk: nothing from ~/.claude
# (CLAUDE.md, hook wiring, MCP registrations) travels there. This wrapper is wired in
# the repo's `.claude/settings.json` for every hook event the standards own and:
#   - is a no-op outside a cloud session (local hosts get the same hooks from
#     ~/.claude/settings.json via sync.ps1, so nothing runs twice);
#   - on SessionStart, clones ~/.agents from Origin if absent, then hands over to
#     ~/.agents/hooks/cloud-session-start.sh (pull + deliver the composed instructions);
#   - on every other event, runs the same gate script a local session would.
# Fail-open by design, like the gates themselves: a clone or script failure is reported
# on stderr and never wedges the session.
set -uo pipefail
event=${1:-}
[ "${CLAUDE_CODE_REMOTE:-}" = "true" ] || exit 0

agents="$HOME/.agents"
remote="${AGENTS_REMOTE:-https://origin.cursor.com/swatto/agent-standards.git}"
# The Origin credential is read from the environment each time git asks for it
# (ORIGIN_TOKEN, optional ORIGIN_USER); nothing is written to disk. Without ORIGIN_TOKEN
# the clone runs unauthenticated, which is the right call when the environment's agent
# proxy attaches the credential itself.
cred_helper='!f() { echo "username=${ORIGIN_USER:-swatto}"; echo "password=$ORIGIN_TOKEN"; }; f'

case $event in
  SessionStart)
    if [ ! -d "$agents/.git" ]; then
      if [ -n "${ORIGIN_TOKEN:-}" ]; then
        git -c credential.helper="$cred_helper" clone --quiet "$remote" "$agents" 2>&1 >/dev/null | tail -3 >&2
      else
        git clone --quiet "$remote" "$agents" 2>&1 >/dev/null | tail -3 >&2
      fi
      if [ ! -d "$agents/.git" ]; then
        echo "agent-standards: could not clone $remote to $agents — this session runs without the central standards" >&2
        exit 0
      fi
      [ -n "${ORIGIN_TOKEN:-}" ] && git -C "$agents" config credential.helper "$cred_helper"
    fi
    script="$agents/hooks/cloud-session-start.sh"
    ;;
  PreToolUse)  script="$agents/hooks/destructive-guard.sh" ;;
  PostToolUse) script="$agents/hooks/fastcheck.sh" ;;
  Stop)        script="$agents/hooks/stop-gate.sh" ;;
  *) echo "agent-standards: unknown hook event '$event'" >&2; exit 0 ;;
esac

[ -f "$script" ] || { echo "agent-standards: $script is missing — ~/.agents predates the cloud bridge; pull it or remove it so the next SessionStart re-clones" >&2; exit 0; }
exec bash "$script"
